### ISSUE TITLE
Game not launching with POM enabled

### ISSUE THREAD

**Issue by Skeithh** [Rain-World-Modding/Pom#5]
Pom (and regionkit) is a dependency for diverse shelters, enabling these two dependencies in the modlist prevents the game from launching. It will start a launch and load for several seconds before closing before you even get to actually see a game screen.

I presume the issue lies with POM as another user has posted stating that enabling this mod specifically causes these issues.

**Comment by thalber** [comment]
a few people had that issue and fixed it by clearing out `rain world/bepinex` folder and verifying game files. do you happen to have modded the game prior to Downpour?

**Comment by Skeithh** [comment]
> a few people had that issue and fixed it by clearing out `rain world/bepinex` folder and verifying game files. do you happen to have modded the game prior to Downpour?

apologies for late reply-
I believe i did not mod the game prior to downpour on this computer (fresh install) but I will see if cleaning out the bepinex folder would fix it and will update here. Perhaps steam cloud decided to invade my game files without me realising it.

**Comment by Skeithh** [comment]
looks like this fixed it! May I suggest leaving a disclaimer about this fix on the mod's page description? I believe it'd help out a lot of folks fix their issues faster :>
