### ISSUE TITLE
Crapload of Warning potentially causing a softlock freeze while saving.

### ISSUE THREAD

**Issue by dalekfan** [Rain-World-Modding/Pom#6]
Got this one in garbage wastes. No exception log, so this will have to do.
[LogOutput.log](https://github.com/Rain-World-Modding/Pom/files/12216546/LogOutput.log)

**Comment by thalber** [comment]
POM warnings are leftover debug lines and don't indicate anything problematic, they'll be removed next update. have you tried disabling some mods to try narrow down the issue?

**Comment by dalekfan** [comment]
Sadly no.

**Comment by thalber** [comment]
log spam is fixed in 2.8.1, i will assume the crash was not related
