### ISSUE TITLE
Massive Log Spam of Warning information

### ISSUE THREAD

**Issue by Dragon-Seeker** [Rain-World-Modding/Pom#7]
Large amounts of Logged info involved with what was stated as "debug" is within every log file and frankly is pretty rough to go through due to such. An update was talked about but nothing has happened, so when might this be dealt with?
[LogOutput(8).log](https://github.com/Rain-World-Modding/Pom/files/12707271/LogOutput.8.log)

**Comment by thalber** [comment]
fixed in 2.8.1

**Comment by Dragon-Seeker** [comment]
Thank you very much for such.
